# Generated by Django 5.0.1 on 2024-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bank_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
