# Generated by Django 5.0.1 on 2024-02-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_bank_transaction_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrupt',
        ),
    ]
